### ISSUE TITLE
Highlighted Links are Unreadable

### ISSUE THREAD

**Issue by amihaiemil** [pragmatic-objects/site#4]
I very often highlight the text I'm reading with my mouse. The CSS of your links seems to not like that:

![image](https://user-images.githubusercontent.com/6305156/75345203-f0706500-58a4-11ea-8d9c-1bcff91a8ac3.png)

![image](https://user-images.githubusercontent.com/6305156/75345333-34636a00-58a5-11ea-930f-9a2e5bfbc7f4.png)

**Comment by skapral** [comment]
@amihaiemil corrected the styling, should be fixed now.
